package com.hut.kwk.model.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;

public class Classroom implements Cloneable, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.room_name
     *
     * @mbg.generated
     */
    private String roomName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.room_space
     *
     * @mbg.generated
     */
    private Integer roomSpace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.room_layer
     *
     * @mbg.generated
     */
    private Integer roomLayer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.room_sign
     *
     * @mbg.generated
     */
    private Integer roomSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.statu
     *
     * @mbg.generated
     */
    private Integer statu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classroom
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    public Classroom(Integer id, String roomName, Integer roomSpace, Integer roomLayer, Integer roomSign, Integer statu, String mark) {
        this.id = id;
        this.roomName = roomName;
        this.roomSpace = roomSpace;
        this.roomLayer = roomLayer;
        this.roomSign = roomSign;
        this.statu = statu;
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    public Classroom() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.id
     *
     * @return the value of classroom.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    public Classroom withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.id
     *
     * @param id the value for classroom.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.room_name
     *
     * @return the value of classroom.room_name
     *
     * @mbg.generated
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    public Classroom withRoomName(String roomName) {
        this.setRoomName(roomName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.room_name
     *
     * @param roomName the value for classroom.room_name
     *
     * @mbg.generated
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.room_space
     *
     * @return the value of classroom.room_space
     *
     * @mbg.generated
     */
    public Integer getRoomSpace() {
        return roomSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    public Classroom withRoomSpace(Integer roomSpace) {
        this.setRoomSpace(roomSpace);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.room_space
     *
     * @param roomSpace the value for classroom.room_space
     *
     * @mbg.generated
     */
    public void setRoomSpace(Integer roomSpace) {
        this.roomSpace = roomSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.room_layer
     *
     * @return the value of classroom.room_layer
     *
     * @mbg.generated
     */
    public Integer getRoomLayer() {
        return roomLayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    public Classroom withRoomLayer(Integer roomLayer) {
        this.setRoomLayer(roomLayer);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.room_layer
     *
     * @param roomLayer the value for classroom.room_layer
     *
     * @mbg.generated
     */
    public void setRoomLayer(Integer roomLayer) {
        this.roomLayer = roomLayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.room_sign
     *
     * @return the value of classroom.room_sign
     *
     * @mbg.generated
     */
    public Integer getRoomSign() {
        return roomSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    public Classroom withRoomSign(Integer roomSign) {
        this.setRoomSign(roomSign);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.room_sign
     *
     * @param roomSign the value for classroom.room_sign
     *
     * @mbg.generated
     */
    public void setRoomSign(Integer roomSign) {
        this.roomSign = roomSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.statu
     *
     * @return the value of classroom.statu
     *
     * @mbg.generated
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    public Classroom withStatu(Integer statu) {
        this.setStatu(statu);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.statu
     *
     * @param statu the value for classroom.statu
     *
     * @mbg.generated
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.mark
     *
     * @return the value of classroom.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    public Classroom withMark(String mark) {
        this.setMark(mark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.mark
     *
     * @param mark the value for classroom.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Classroom other = (Classroom) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoomName() == null ? other.getRoomName() == null : this.getRoomName().equals(other.getRoomName()))
            && (this.getRoomSpace() == null ? other.getRoomSpace() == null : this.getRoomSpace().equals(other.getRoomSpace()))
            && (this.getRoomLayer() == null ? other.getRoomLayer() == null : this.getRoomLayer().equals(other.getRoomLayer()))
            && (this.getRoomSign() == null ? other.getRoomSign() == null : this.getRoomSign().equals(other.getRoomSign()))
            && (this.getStatu() == null ? other.getStatu() == null : this.getStatu().equals(other.getStatu()))
            && (this.getMark() == null ? other.getMark() == null : this.getMark().equals(other.getMark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoomName() == null) ? 0 : getRoomName().hashCode());
        result = prime * result + ((getRoomSpace() == null) ? 0 : getRoomSpace().hashCode());
        result = prime * result + ((getRoomLayer() == null) ? 0 : getRoomLayer().hashCode());
        result = prime * result + ((getRoomSign() == null) ? 0 : getRoomSign().hashCode());
        result = prime * result + ((getStatu() == null) ? 0 : getStatu().hashCode());
        result = prime * result + ((getMark() == null) ? 0 : getMark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roomName=").append(roomName);
        sb.append(", roomSpace=").append(roomSpace);
        sb.append(", roomLayer=").append(roomLayer);
        sb.append(", roomSign=").append(roomSign);
        sb.append(", statu=").append(statu);
        sb.append(", mark=").append(mark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Override
    public Classroom clone() throws CloneNotSupportedException {
        return (Classroom) super.clone();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table classroom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        roomName("room_name", "roomName", "VARCHAR", false),
        roomSpace("room_space", "roomSpace", "INTEGER", false),
        roomLayer("room_layer", "roomLayer", "INTEGER", false),
        roomSign("room_sign", "roomSign", "INTEGER", false),
        statu("statu", "statu", "INTEGER", false),
        mark("mark", "mark", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table classroom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}