package com.hut.kwk.model.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;

public class CourseTable implements Cloneable, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.arr_id
     *
     * @mbg.generated
     */
    private Integer arrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.room_id
     *
     * @mbg.generated
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.techer_id
     *
     * @mbg.generated
     */
    private Integer techerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.seme_id
     *
     * @mbg.generated
     */
    private Integer semeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.seme_name
     *
     * @mbg.generated
     */
    private String semeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.time_id
     *
     * @mbg.generated
     */
    private Integer timeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.time_name
     *
     * @mbg.generated
     */
    private String timeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.room_name
     *
     * @mbg.generated
     */
    private String roomName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.techer_name
     *
     * @mbg.generated
     */
    private String techerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.statu
     *
     * @mbg.generated
     */
    private Integer statu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.temporary
     *
     * @mbg.generated
     */
    private Integer temporary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_table.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_table
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable(Integer id, Integer arrId, Integer courseId, Integer classId, Integer roomId, Integer techerId, Integer semeId, String semeName, Integer timeId, String timeName, String courseName, String className, String roomName, String techerName, Integer statu, Integer temporary, String mark) {
        this.id = id;
        this.arrId = arrId;
        this.courseId = courseId;
        this.classId = classId;
        this.roomId = roomId;
        this.techerId = techerId;
        this.semeId = semeId;
        this.semeName = semeName;
        this.timeId = timeId;
        this.timeName = timeName;
        this.courseName = courseName;
        this.className = className;
        this.roomName = roomName;
        this.techerName = techerName;
        this.statu = statu;
        this.temporary = temporary;
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.id
     *
     * @return the value of course_table.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.id
     *
     * @param id the value for course_table.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.arr_id
     *
     * @return the value of course_table.arr_id
     *
     * @mbg.generated
     */
    public Integer getArrId() {
        return arrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withArrId(Integer arrId) {
        this.setArrId(arrId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.arr_id
     *
     * @param arrId the value for course_table.arr_id
     *
     * @mbg.generated
     */
    public void setArrId(Integer arrId) {
        this.arrId = arrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.course_id
     *
     * @return the value of course_table.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withCourseId(Integer courseId) {
        this.setCourseId(courseId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.course_id
     *
     * @param courseId the value for course_table.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.class_id
     *
     * @return the value of course_table.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withClassId(Integer classId) {
        this.setClassId(classId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.class_id
     *
     * @param classId the value for course_table.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.room_id
     *
     * @return the value of course_table.room_id
     *
     * @mbg.generated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withRoomId(Integer roomId) {
        this.setRoomId(roomId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.room_id
     *
     * @param roomId the value for course_table.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.techer_id
     *
     * @return the value of course_table.techer_id
     *
     * @mbg.generated
     */
    public Integer getTecherId() {
        return techerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withTecherId(Integer techerId) {
        this.setTecherId(techerId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.techer_id
     *
     * @param techerId the value for course_table.techer_id
     *
     * @mbg.generated
     */
    public void setTecherId(Integer techerId) {
        this.techerId = techerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.seme_id
     *
     * @return the value of course_table.seme_id
     *
     * @mbg.generated
     */
    public Integer getSemeId() {
        return semeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withSemeId(Integer semeId) {
        this.setSemeId(semeId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.seme_id
     *
     * @param semeId the value for course_table.seme_id
     *
     * @mbg.generated
     */
    public void setSemeId(Integer semeId) {
        this.semeId = semeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.seme_name
     *
     * @return the value of course_table.seme_name
     *
     * @mbg.generated
     */
    public String getSemeName() {
        return semeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withSemeName(String semeName) {
        this.setSemeName(semeName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.seme_name
     *
     * @param semeName the value for course_table.seme_name
     *
     * @mbg.generated
     */
    public void setSemeName(String semeName) {
        this.semeName = semeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.time_id
     *
     * @return the value of course_table.time_id
     *
     * @mbg.generated
     */
    public Integer getTimeId() {
        return timeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withTimeId(Integer timeId) {
        this.setTimeId(timeId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.time_id
     *
     * @param timeId the value for course_table.time_id
     *
     * @mbg.generated
     */
    public void setTimeId(Integer timeId) {
        this.timeId = timeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.time_name
     *
     * @return the value of course_table.time_name
     *
     * @mbg.generated
     */
    public String getTimeName() {
        return timeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withTimeName(String timeName) {
        this.setTimeName(timeName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.time_name
     *
     * @param timeName the value for course_table.time_name
     *
     * @mbg.generated
     */
    public void setTimeName(String timeName) {
        this.timeName = timeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.course_name
     *
     * @return the value of course_table.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withCourseName(String courseName) {
        this.setCourseName(courseName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.course_name
     *
     * @param courseName the value for course_table.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.class_name
     *
     * @return the value of course_table.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withClassName(String className) {
        this.setClassName(className);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.class_name
     *
     * @param className the value for course_table.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.room_name
     *
     * @return the value of course_table.room_name
     *
     * @mbg.generated
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withRoomName(String roomName) {
        this.setRoomName(roomName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.room_name
     *
     * @param roomName the value for course_table.room_name
     *
     * @mbg.generated
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.techer_name
     *
     * @return the value of course_table.techer_name
     *
     * @mbg.generated
     */
    public String getTecherName() {
        return techerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withTecherName(String techerName) {
        this.setTecherName(techerName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.techer_name
     *
     * @param techerName the value for course_table.techer_name
     *
     * @mbg.generated
     */
    public void setTecherName(String techerName) {
        this.techerName = techerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.statu
     *
     * @return the value of course_table.statu
     *
     * @mbg.generated
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withStatu(Integer statu) {
        this.setStatu(statu);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.statu
     *
     * @param statu the value for course_table.statu
     *
     * @mbg.generated
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.temporary
     *
     * @return the value of course_table.temporary
     *
     * @mbg.generated
     */
    public Integer getTemporary() {
        return temporary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withTemporary(Integer temporary) {
        this.setTemporary(temporary);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.temporary
     *
     * @param temporary the value for course_table.temporary
     *
     * @mbg.generated
     */
    public void setTemporary(Integer temporary) {
        this.temporary = temporary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_table.mark
     *
     * @return the value of course_table.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTable withMark(String mark) {
        this.setMark(mark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_table.mark
     *
     * @param mark the value for course_table.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CourseTable other = (CourseTable) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getArrId() == null ? other.getArrId() == null : this.getArrId().equals(other.getArrId()))
            && (this.getCourseId() == null ? other.getCourseId() == null : this.getCourseId().equals(other.getCourseId()))
            && (this.getClassId() == null ? other.getClassId() == null : this.getClassId().equals(other.getClassId()))
            && (this.getRoomId() == null ? other.getRoomId() == null : this.getRoomId().equals(other.getRoomId()))
            && (this.getTecherId() == null ? other.getTecherId() == null : this.getTecherId().equals(other.getTecherId()))
            && (this.getSemeId() == null ? other.getSemeId() == null : this.getSemeId().equals(other.getSemeId()))
            && (this.getSemeName() == null ? other.getSemeName() == null : this.getSemeName().equals(other.getSemeName()))
            && (this.getTimeId() == null ? other.getTimeId() == null : this.getTimeId().equals(other.getTimeId()))
            && (this.getTimeName() == null ? other.getTimeName() == null : this.getTimeName().equals(other.getTimeName()))
            && (this.getCourseName() == null ? other.getCourseName() == null : this.getCourseName().equals(other.getCourseName()))
            && (this.getClassName() == null ? other.getClassName() == null : this.getClassName().equals(other.getClassName()))
            && (this.getRoomName() == null ? other.getRoomName() == null : this.getRoomName().equals(other.getRoomName()))
            && (this.getTecherName() == null ? other.getTecherName() == null : this.getTecherName().equals(other.getTecherName()))
            && (this.getStatu() == null ? other.getStatu() == null : this.getStatu().equals(other.getStatu()))
            && (this.getTemporary() == null ? other.getTemporary() == null : this.getTemporary().equals(other.getTemporary()))
            && (this.getMark() == null ? other.getMark() == null : this.getMark().equals(other.getMark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getArrId() == null) ? 0 : getArrId().hashCode());
        result = prime * result + ((getCourseId() == null) ? 0 : getCourseId().hashCode());
        result = prime * result + ((getClassId() == null) ? 0 : getClassId().hashCode());
        result = prime * result + ((getRoomId() == null) ? 0 : getRoomId().hashCode());
        result = prime * result + ((getTecherId() == null) ? 0 : getTecherId().hashCode());
        result = prime * result + ((getSemeId() == null) ? 0 : getSemeId().hashCode());
        result = prime * result + ((getSemeName() == null) ? 0 : getSemeName().hashCode());
        result = prime * result + ((getTimeId() == null) ? 0 : getTimeId().hashCode());
        result = prime * result + ((getTimeName() == null) ? 0 : getTimeName().hashCode());
        result = prime * result + ((getCourseName() == null) ? 0 : getCourseName().hashCode());
        result = prime * result + ((getClassName() == null) ? 0 : getClassName().hashCode());
        result = prime * result + ((getRoomName() == null) ? 0 : getRoomName().hashCode());
        result = prime * result + ((getTecherName() == null) ? 0 : getTecherName().hashCode());
        result = prime * result + ((getStatu() == null) ? 0 : getStatu().hashCode());
        result = prime * result + ((getTemporary() == null) ? 0 : getTemporary().hashCode());
        result = prime * result + ((getMark() == null) ? 0 : getMark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", arrId=").append(arrId);
        sb.append(", courseId=").append(courseId);
        sb.append(", classId=").append(classId);
        sb.append(", roomId=").append(roomId);
        sb.append(", techerId=").append(techerId);
        sb.append(", semeId=").append(semeId);
        sb.append(", semeName=").append(semeName);
        sb.append(", timeId=").append(timeId);
        sb.append(", timeName=").append(timeName);
        sb.append(", courseName=").append(courseName);
        sb.append(", className=").append(className);
        sb.append(", roomName=").append(roomName);
        sb.append(", techerName=").append(techerName);
        sb.append(", statu=").append(statu);
        sb.append(", temporary=").append(temporary);
        sb.append(", mark=").append(mark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Override
    public CourseTable clone() throws CloneNotSupportedException {
        return (CourseTable) super.clone();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table course_table
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        arrId("arr_id", "arrId", "INTEGER", false),
        courseId("course_id", "courseId", "INTEGER", false),
        classId("class_id", "classId", "INTEGER", false),
        roomId("room_id", "roomId", "INTEGER", false),
        techerId("techer_id", "techerId", "INTEGER", false),
        semeId("seme_id", "semeId", "INTEGER", false),
        semeName("seme_name", "semeName", "VARCHAR", false),
        timeId("time_id", "timeId", "INTEGER", false),
        timeName("time_name", "timeName", "VARCHAR", false),
        courseName("course_name", "courseName", "VARCHAR", false),
        className("class_name", "className", "VARCHAR", false),
        roomName("room_name", "roomName", "VARCHAR", false),
        techerName("techer_name", "techerName", "VARCHAR", false),
        statu("statu", "statu", "INTEGER", false),
        temporary("temporary", "temporary", "INTEGER", true),
        mark("mark", "mark", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table course_table
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}