package com.hut.kwk.model.entity;

import java.util.ArrayList;
import java.util.List;

public class CourseTableQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_table
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_table
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_table
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_table
     *
     * @mbg.generated
     */
    protected Boolean forUpdate = false;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public CourseTableQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public void setForUpdate(Boolean forUpdate) {
        this.forUpdate = forUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public Boolean isForUpdate() {
        return forUpdate;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course_table
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andArrIdIsNull() {
            addCriterion("arr_id is null");
            return (Criteria) this;
        }

        public Criteria andArrIdIsNotNull() {
            addCriterion("arr_id is not null");
            return (Criteria) this;
        }

        public Criteria andArrIdEqualTo(Integer value) {
            addCriterion("arr_id =", value, "arrId");
            return (Criteria) this;
        }

        public Criteria andArrIdNotEqualTo(Integer value) {
            addCriterion("arr_id <>", value, "arrId");
            return (Criteria) this;
        }

        public Criteria andArrIdGreaterThan(Integer value) {
            addCriterion("arr_id >", value, "arrId");
            return (Criteria) this;
        }

        public Criteria andArrIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("arr_id >=", value, "arrId");
            return (Criteria) this;
        }

        public Criteria andArrIdLessThan(Integer value) {
            addCriterion("arr_id <", value, "arrId");
            return (Criteria) this;
        }

        public Criteria andArrIdLessThanOrEqualTo(Integer value) {
            addCriterion("arr_id <=", value, "arrId");
            return (Criteria) this;
        }

        public Criteria andArrIdIn(List<Integer> values) {
            addCriterion("arr_id in", values, "arrId");
            return (Criteria) this;
        }

        public Criteria andArrIdNotIn(List<Integer> values) {
            addCriterion("arr_id not in", values, "arrId");
            return (Criteria) this;
        }

        public Criteria andArrIdBetween(Integer value1, Integer value2) {
            addCriterion("arr_id between", value1, value2, "arrId");
            return (Criteria) this;
        }

        public Criteria andArrIdNotBetween(Integer value1, Integer value2) {
            addCriterion("arr_id not between", value1, value2, "arrId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(Integer value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(Integer value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(Integer value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(Integer value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(Integer value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<Integer> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<Integer> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(Integer value1, Integer value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Integer value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Integer value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Integer value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Integer value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Integer> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Integer> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Integer value1, Integer value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andTecherIdIsNull() {
            addCriterion("techer_id is null");
            return (Criteria) this;
        }

        public Criteria andTecherIdIsNotNull() {
            addCriterion("techer_id is not null");
            return (Criteria) this;
        }

        public Criteria andTecherIdEqualTo(Integer value) {
            addCriterion("techer_id =", value, "techerId");
            return (Criteria) this;
        }

        public Criteria andTecherIdNotEqualTo(Integer value) {
            addCriterion("techer_id <>", value, "techerId");
            return (Criteria) this;
        }

        public Criteria andTecherIdGreaterThan(Integer value) {
            addCriterion("techer_id >", value, "techerId");
            return (Criteria) this;
        }

        public Criteria andTecherIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("techer_id >=", value, "techerId");
            return (Criteria) this;
        }

        public Criteria andTecherIdLessThan(Integer value) {
            addCriterion("techer_id <", value, "techerId");
            return (Criteria) this;
        }

        public Criteria andTecherIdLessThanOrEqualTo(Integer value) {
            addCriterion("techer_id <=", value, "techerId");
            return (Criteria) this;
        }

        public Criteria andTecherIdIn(List<Integer> values) {
            addCriterion("techer_id in", values, "techerId");
            return (Criteria) this;
        }

        public Criteria andTecherIdNotIn(List<Integer> values) {
            addCriterion("techer_id not in", values, "techerId");
            return (Criteria) this;
        }

        public Criteria andTecherIdBetween(Integer value1, Integer value2) {
            addCriterion("techer_id between", value1, value2, "techerId");
            return (Criteria) this;
        }

        public Criteria andTecherIdNotBetween(Integer value1, Integer value2) {
            addCriterion("techer_id not between", value1, value2, "techerId");
            return (Criteria) this;
        }

        public Criteria andSemeIdIsNull() {
            addCriterion("seme_id is null");
            return (Criteria) this;
        }

        public Criteria andSemeIdIsNotNull() {
            addCriterion("seme_id is not null");
            return (Criteria) this;
        }

        public Criteria andSemeIdEqualTo(Integer value) {
            addCriterion("seme_id =", value, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeIdNotEqualTo(Integer value) {
            addCriterion("seme_id <>", value, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeIdGreaterThan(Integer value) {
            addCriterion("seme_id >", value, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("seme_id >=", value, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeIdLessThan(Integer value) {
            addCriterion("seme_id <", value, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeIdLessThanOrEqualTo(Integer value) {
            addCriterion("seme_id <=", value, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeIdIn(List<Integer> values) {
            addCriterion("seme_id in", values, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeIdNotIn(List<Integer> values) {
            addCriterion("seme_id not in", values, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeIdBetween(Integer value1, Integer value2) {
            addCriterion("seme_id between", value1, value2, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("seme_id not between", value1, value2, "semeId");
            return (Criteria) this;
        }

        public Criteria andSemeNameIsNull() {
            addCriterion("seme_name is null");
            return (Criteria) this;
        }

        public Criteria andSemeNameIsNotNull() {
            addCriterion("seme_name is not null");
            return (Criteria) this;
        }

        public Criteria andSemeNameEqualTo(String value) {
            addCriterion("seme_name =", value, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameNotEqualTo(String value) {
            addCriterion("seme_name <>", value, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameGreaterThan(String value) {
            addCriterion("seme_name >", value, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameGreaterThanOrEqualTo(String value) {
            addCriterion("seme_name >=", value, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameLessThan(String value) {
            addCriterion("seme_name <", value, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameLessThanOrEqualTo(String value) {
            addCriterion("seme_name <=", value, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameLike(String value) {
            addCriterion("seme_name like", value, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameNotLike(String value) {
            addCriterion("seme_name not like", value, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameIn(List<String> values) {
            addCriterion("seme_name in", values, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameNotIn(List<String> values) {
            addCriterion("seme_name not in", values, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameBetween(String value1, String value2) {
            addCriterion("seme_name between", value1, value2, "semeName");
            return (Criteria) this;
        }

        public Criteria andSemeNameNotBetween(String value1, String value2) {
            addCriterion("seme_name not between", value1, value2, "semeName");
            return (Criteria) this;
        }

        public Criteria andTimeIdIsNull() {
            addCriterion("time_id is null");
            return (Criteria) this;
        }

        public Criteria andTimeIdIsNotNull() {
            addCriterion("time_id is not null");
            return (Criteria) this;
        }

        public Criteria andTimeIdEqualTo(Integer value) {
            addCriterion("time_id =", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdNotEqualTo(Integer value) {
            addCriterion("time_id <>", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdGreaterThan(Integer value) {
            addCriterion("time_id >", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_id >=", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdLessThan(Integer value) {
            addCriterion("time_id <", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdLessThanOrEqualTo(Integer value) {
            addCriterion("time_id <=", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdIn(List<Integer> values) {
            addCriterion("time_id in", values, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdNotIn(List<Integer> values) {
            addCriterion("time_id not in", values, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdBetween(Integer value1, Integer value2) {
            addCriterion("time_id between", value1, value2, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("time_id not between", value1, value2, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeNameIsNull() {
            addCriterion("time_name is null");
            return (Criteria) this;
        }

        public Criteria andTimeNameIsNotNull() {
            addCriterion("time_name is not null");
            return (Criteria) this;
        }

        public Criteria andTimeNameEqualTo(String value) {
            addCriterion("time_name =", value, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameNotEqualTo(String value) {
            addCriterion("time_name <>", value, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameGreaterThan(String value) {
            addCriterion("time_name >", value, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameGreaterThanOrEqualTo(String value) {
            addCriterion("time_name >=", value, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameLessThan(String value) {
            addCriterion("time_name <", value, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameLessThanOrEqualTo(String value) {
            addCriterion("time_name <=", value, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameLike(String value) {
            addCriterion("time_name like", value, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameNotLike(String value) {
            addCriterion("time_name not like", value, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameIn(List<String> values) {
            addCriterion("time_name in", values, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameNotIn(List<String> values) {
            addCriterion("time_name not in", values, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameBetween(String value1, String value2) {
            addCriterion("time_name between", value1, value2, "timeName");
            return (Criteria) this;
        }

        public Criteria andTimeNameNotBetween(String value1, String value2) {
            addCriterion("time_name not between", value1, value2, "timeName");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNull() {
            addCriterion("course_name is null");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNotNull() {
            addCriterion("course_name is not null");
            return (Criteria) this;
        }

        public Criteria andCourseNameEqualTo(String value) {
            addCriterion("course_name =", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotEqualTo(String value) {
            addCriterion("course_name <>", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThan(String value) {
            addCriterion("course_name >", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThanOrEqualTo(String value) {
            addCriterion("course_name >=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThan(String value) {
            addCriterion("course_name <", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThanOrEqualTo(String value) {
            addCriterion("course_name <=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLike(String value) {
            addCriterion("course_name like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotLike(String value) {
            addCriterion("course_name not like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameIn(List<String> values) {
            addCriterion("course_name in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotIn(List<String> values) {
            addCriterion("course_name not in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameBetween(String value1, String value2) {
            addCriterion("course_name between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotBetween(String value1, String value2) {
            addCriterion("course_name not between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("class_name is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("class_name is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("class_name =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("class_name <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("class_name >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_name >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("class_name <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("class_name <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("class_name like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("class_name not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("class_name in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("class_name not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("class_name between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("class_name not between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNull() {
            addCriterion("room_name is null");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNotNull() {
            addCriterion("room_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNameEqualTo(String value) {
            addCriterion("room_name =", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotEqualTo(String value) {
            addCriterion("room_name <>", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThan(String value) {
            addCriterion("room_name >", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("room_name >=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThan(String value) {
            addCriterion("room_name <", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThanOrEqualTo(String value) {
            addCriterion("room_name <=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLike(String value) {
            addCriterion("room_name like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotLike(String value) {
            addCriterion("room_name not like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameIn(List<String> values) {
            addCriterion("room_name in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotIn(List<String> values) {
            addCriterion("room_name not in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameBetween(String value1, String value2) {
            addCriterion("room_name between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotBetween(String value1, String value2) {
            addCriterion("room_name not between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andTecherNameIsNull() {
            addCriterion("techer_name is null");
            return (Criteria) this;
        }

        public Criteria andTecherNameIsNotNull() {
            addCriterion("techer_name is not null");
            return (Criteria) this;
        }

        public Criteria andTecherNameEqualTo(String value) {
            addCriterion("techer_name =", value, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameNotEqualTo(String value) {
            addCriterion("techer_name <>", value, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameGreaterThan(String value) {
            addCriterion("techer_name >", value, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameGreaterThanOrEqualTo(String value) {
            addCriterion("techer_name >=", value, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameLessThan(String value) {
            addCriterion("techer_name <", value, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameLessThanOrEqualTo(String value) {
            addCriterion("techer_name <=", value, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameLike(String value) {
            addCriterion("techer_name like", value, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameNotLike(String value) {
            addCriterion("techer_name not like", value, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameIn(List<String> values) {
            addCriterion("techer_name in", values, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameNotIn(List<String> values) {
            addCriterion("techer_name not in", values, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameBetween(String value1, String value2) {
            addCriterion("techer_name between", value1, value2, "techerName");
            return (Criteria) this;
        }

        public Criteria andTecherNameNotBetween(String value1, String value2) {
            addCriterion("techer_name not between", value1, value2, "techerName");
            return (Criteria) this;
        }

        public Criteria andStatuIsNull() {
            addCriterion("statu is null");
            return (Criteria) this;
        }

        public Criteria andStatuIsNotNull() {
            addCriterion("statu is not null");
            return (Criteria) this;
        }

        public Criteria andStatuEqualTo(Integer value) {
            addCriterion("statu =", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuNotEqualTo(Integer value) {
            addCriterion("statu <>", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuGreaterThan(Integer value) {
            addCriterion("statu >", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuGreaterThanOrEqualTo(Integer value) {
            addCriterion("statu >=", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuLessThan(Integer value) {
            addCriterion("statu <", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuLessThanOrEqualTo(Integer value) {
            addCriterion("statu <=", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuIn(List<Integer> values) {
            addCriterion("statu in", values, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuNotIn(List<Integer> values) {
            addCriterion("statu not in", values, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuBetween(Integer value1, Integer value2) {
            addCriterion("statu between", value1, value2, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuNotBetween(Integer value1, Integer value2) {
            addCriterion("statu not between", value1, value2, "statu");
            return (Criteria) this;
        }

        public Criteria andTemporaryIsNull() {
            addCriterion("`temporary` is null");
            return (Criteria) this;
        }

        public Criteria andTemporaryIsNotNull() {
            addCriterion("`temporary` is not null");
            return (Criteria) this;
        }

        public Criteria andTemporaryEqualTo(Integer value) {
            addCriterion("`temporary` =", value, "temporary");
            return (Criteria) this;
        }

        public Criteria andTemporaryNotEqualTo(Integer value) {
            addCriterion("`temporary` <>", value, "temporary");
            return (Criteria) this;
        }

        public Criteria andTemporaryGreaterThan(Integer value) {
            addCriterion("`temporary` >", value, "temporary");
            return (Criteria) this;
        }

        public Criteria andTemporaryGreaterThanOrEqualTo(Integer value) {
            addCriterion("`temporary` >=", value, "temporary");
            return (Criteria) this;
        }

        public Criteria andTemporaryLessThan(Integer value) {
            addCriterion("`temporary` <", value, "temporary");
            return (Criteria) this;
        }

        public Criteria andTemporaryLessThanOrEqualTo(Integer value) {
            addCriterion("`temporary` <=", value, "temporary");
            return (Criteria) this;
        }

        public Criteria andTemporaryIn(List<Integer> values) {
            addCriterion("`temporary` in", values, "temporary");
            return (Criteria) this;
        }

        public Criteria andTemporaryNotIn(List<Integer> values) {
            addCriterion("`temporary` not in", values, "temporary");
            return (Criteria) this;
        }

        public Criteria andTemporaryBetween(Integer value1, Integer value2) {
            addCriterion("`temporary` between", value1, value2, "temporary");
            return (Criteria) this;
        }

        public Criteria andTemporaryNotBetween(Integer value1, Integer value2) {
            addCriterion("`temporary` not between", value1, value2, "temporary");
            return (Criteria) this;
        }

        public Criteria andMarkIsNull() {
            addCriterion("mark is null");
            return (Criteria) this;
        }

        public Criteria andMarkIsNotNull() {
            addCriterion("mark is not null");
            return (Criteria) this;
        }

        public Criteria andMarkEqualTo(String value) {
            addCriterion("mark =", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotEqualTo(String value) {
            addCriterion("mark <>", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThan(String value) {
            addCriterion("mark >", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThanOrEqualTo(String value) {
            addCriterion("mark >=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThan(String value) {
            addCriterion("mark <", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThanOrEqualTo(String value) {
            addCriterion("mark <=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLike(String value) {
            addCriterion("mark like", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotLike(String value) {
            addCriterion("mark not like", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkIn(List<String> values) {
            addCriterion("mark in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotIn(List<String> values) {
            addCriterion("mark not in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkBetween(String value1, String value2) {
            addCriterion("mark between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotBetween(String value1, String value2) {
            addCriterion("mark not between", value1, value2, "mark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course_table
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course_table
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}