package com.hut.kwk.model.mapper;

import com.hut.kwk.model.entity.Arrange;
import com.hut.kwk.model.entity.ArrangeQuery;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface ArrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    long countByExample(ArrangeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    int deleteByExample(ArrangeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    @Delete({
        "delete from arrange",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    @Insert({
        "insert into arrange (course_id, class_id, ",
        "room_id, techer_id, ",
        "seme_id, course_name, ",
        "class_name, room_name, ",
        "techer_name, star_week, ",
        "end_week, srd, statu, ",
        "mark)",
        "values (#{courseId,jdbcType=INTEGER}, #{classId,jdbcType=INTEGER}, ",
        "#{roomId,jdbcType=INTEGER}, #{techerId,jdbcType=INTEGER}, ",
        "#{semeId,jdbcType=INTEGER}, #{courseName,jdbcType=VARCHAR}, ",
        "#{className,jdbcType=VARCHAR}, #{roomName,jdbcType=VARCHAR}, ",
        "#{techerName,jdbcType=VARCHAR}, #{starWeek,jdbcType=INTEGER}, ",
        "#{endWeek,jdbcType=INTEGER}, #{srd,jdbcType=INTEGER}, #{statu,jdbcType=INTEGER}, ",
        "#{mark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Arrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    int insertSelective(Arrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    List<Arrange> selectByExampleWithRowbounds(ArrangeQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Arrange selectOneByExample(ArrangeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    List<Arrange> selectByExample(ArrangeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, course_id, class_id, room_id, techer_id, seme_id, course_name, class_name, ",
        "room_name, techer_name, star_week, end_week, srd, statu, mark",
        "from arrange",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.hut.kwk.model.mapper.ArrangeMapper.BaseResultMap")
    Arrange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Arrange record, @Param("example") ArrangeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Arrange record, @Param("example") ArrangeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Arrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    @Update({
        "update arrange",
        "set course_id = #{courseId,jdbcType=INTEGER},",
          "class_id = #{classId,jdbcType=INTEGER},",
          "room_id = #{roomId,jdbcType=INTEGER},",
          "techer_id = #{techerId,jdbcType=INTEGER},",
          "seme_id = #{semeId,jdbcType=INTEGER},",
          "course_name = #{courseName,jdbcType=VARCHAR},",
          "class_name = #{className,jdbcType=VARCHAR},",
          "room_name = #{roomName,jdbcType=VARCHAR},",
          "techer_name = #{techerName,jdbcType=VARCHAR},",
          "star_week = #{starWeek,jdbcType=INTEGER},",
          "end_week = #{endWeek,jdbcType=INTEGER},",
          "srd = #{srd,jdbcType=INTEGER},",
          "statu = #{statu,jdbcType=INTEGER},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Arrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    int insertOrUpdate(Arrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     */
    int insertOrUpdateSelective(Arrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Arrange> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arrange
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Arrange> list, @Param("selective") Arrange.Column ... selective);
}