package com.hut.kwk.model.mapper;

import com.hut.kwk.model.entity.Classroom;
import com.hut.kwk.model.entity.ClassroomQuery;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
@Mapper
public interface ClassroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    long countByExample(ClassroomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    int deleteByExample(ClassroomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    @Delete({
        "delete from classroom",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    @Insert({
        "insert into classroom (room_name, room_space, ",
        "room_layer, room_sign, ",
        "statu, mark)",
        "values (#{roomName,jdbcType=VARCHAR}, #{roomSpace,jdbcType=INTEGER}, ",
        "#{roomLayer,jdbcType=INTEGER}, #{roomSign,jdbcType=INTEGER}, ",
        "#{statu,jdbcType=INTEGER}, #{mark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    int insertSelective(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    List<Classroom> selectByExampleWithRowbounds(ClassroomQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Classroom selectOneByExample(ClassroomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    List<Classroom> selectByExample(ClassroomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, room_name, room_space, room_layer, room_sign, statu, mark",
        "from classroom",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.hut.kwk.model.mapper.ClassroomMapper.BaseResultMap")
    Classroom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Classroom record, @Param("example") ClassroomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Classroom record, @Param("example") ClassroomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    @Update({
        "update classroom",
        "set room_name = #{roomName,jdbcType=VARCHAR},",
          "room_space = #{roomSpace,jdbcType=INTEGER},",
          "room_layer = #{roomLayer,jdbcType=INTEGER},",
          "room_sign = #{roomSign,jdbcType=INTEGER},",
          "statu = #{statu,jdbcType=INTEGER},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    int insertOrUpdate(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     */
    int insertOrUpdateSelective(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Classroom> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Classroom> list, @Param("selective") Classroom.Column ... selective);
}