package com.hut.kwk.model.mapper;

import com.hut.kwk.model.entity.CourseTable;
import com.hut.kwk.model.entity.CourseTableQuery;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
@Mapper
public interface CourseTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    long countByExample(CourseTableQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    int deleteByExample(CourseTableQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    @Delete({
        "delete from course_table",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    @Insert({
        "insert into course_table (arr_id, course_id, ",
        "class_id, room_id, ",
        "techer_id, seme_id, ",
        "seme_name, time_id, ",
        "time_name, course_name, ",
        "class_name, room_name, ",
        "techer_name, statu, ",
        "`temporary`, mark)",
        "values (#{arrId,jdbcType=INTEGER}, #{courseId,jdbcType=INTEGER}, ",
        "#{classId,jdbcType=INTEGER}, #{roomId,jdbcType=INTEGER}, ",
        "#{techerId,jdbcType=INTEGER}, #{semeId,jdbcType=INTEGER}, ",
        "#{semeName,jdbcType=VARCHAR}, #{timeId,jdbcType=INTEGER}, ",
        "#{timeName,jdbcType=VARCHAR}, #{courseName,jdbcType=VARCHAR}, ",
        "#{className,jdbcType=VARCHAR}, #{roomName,jdbcType=VARCHAR}, ",
        "#{techerName,jdbcType=VARCHAR}, #{statu,jdbcType=INTEGER}, ",
        "#{temporary,jdbcType=INTEGER}, #{mark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CourseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    int insertSelective(CourseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    List<CourseTable> selectByExampleWithRowbounds(CourseTableQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CourseTable selectOneByExample(CourseTableQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    List<CourseTable> selectByExample(CourseTableQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, arr_id, course_id, class_id, room_id, techer_id, seme_id, seme_name, time_id, ",
        "time_name, course_name, class_name, room_name, techer_name, statu, `temporary`, ",
        "mark",
        "from course_table",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.hut.kwk.model.mapper.CourseTableMapper.BaseResultMap")
    CourseTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CourseTable record, @Param("example") CourseTableQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CourseTable record, @Param("example") CourseTableQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CourseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    @Update({
        "update course_table",
        "set arr_id = #{arrId,jdbcType=INTEGER},",
          "course_id = #{courseId,jdbcType=INTEGER},",
          "class_id = #{classId,jdbcType=INTEGER},",
          "room_id = #{roomId,jdbcType=INTEGER},",
          "techer_id = #{techerId,jdbcType=INTEGER},",
          "seme_id = #{semeId,jdbcType=INTEGER},",
          "seme_name = #{semeName,jdbcType=VARCHAR},",
          "time_id = #{timeId,jdbcType=INTEGER},",
          "time_name = #{timeName,jdbcType=VARCHAR},",
          "course_name = #{courseName,jdbcType=VARCHAR},",
          "class_name = #{className,jdbcType=VARCHAR},",
          "room_name = #{roomName,jdbcType=VARCHAR},",
          "techer_name = #{techerName,jdbcType=VARCHAR},",
          "statu = #{statu,jdbcType=INTEGER},",
          "`temporary` = #{temporary,jdbcType=INTEGER},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CourseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    int insertOrUpdate(CourseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     */
    int insertOrUpdateSelective(CourseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CourseTable> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CourseTable> list, @Param("selective") CourseTable.Column ... selective);
}