package com.hut.kwk.model.mapper;

import com.hut.kwk.model.entity.Semester;
import com.hut.kwk.model.entity.SemesterQuery;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
@Mapper
public interface SemesterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    long countByExample(SemesterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    int deleteByExample(SemesterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    @Delete({
        "delete from semester",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    @Insert({
        "insert into semester (`year`, semester, ",
        "week_count, statu, ",
        "mark)",
        "values (#{year,jdbcType=VARCHAR}, #{semester,jdbcType=VARCHAR}, ",
        "#{weekCount,jdbcType=INTEGER}, #{statu,jdbcType=INTEGER}, ",
        "#{mark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Semester record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    int insertSelective(Semester record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    List<Semester> selectByExampleWithRowbounds(SemesterQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Semester selectOneByExample(SemesterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    List<Semester> selectByExample(SemesterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, `year`, semester, week_count, statu, mark",
        "from semester",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.hut.kwk.model.mapper.SemesterMapper.BaseResultMap")
    Semester selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Semester record, @Param("example") SemesterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Semester record, @Param("example") SemesterQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Semester record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    @Update({
        "update semester",
        "set `year` = #{year,jdbcType=VARCHAR},",
          "semester = #{semester,jdbcType=VARCHAR},",
          "week_count = #{weekCount,jdbcType=INTEGER},",
          "statu = #{statu,jdbcType=INTEGER},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Semester record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    int insertOrUpdate(Semester record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     */
    int insertOrUpdateSelective(Semester record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Semester> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semester
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Semester> list, @Param("selective") Semester.Column ... selective);
}